version: '3.7'
services:
  nginx:
    image: "nginx:1.19"
    ports:
      - 5000:8080
    links:
      - "chat:chat"
    depends_on:
      - chat
    volumes:
      - nginx:/etc/nginx/conf.d/
    networks:
      - chatbot-network
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  web:
    build: 
      context: ./../../../
      dockerfile: ./src/main/docker/nodejs/Dockerfile
    command:  yarn cross-env  PORT=3001 HOST=0.0.0.0 NODE_ENV=production BASE=/loginchat node server/index.js
    #volumes:
    #  - nodejs:/nodejs/
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    links:
      - "mongodb:mongodb"
      - "api:api"
    networks:
      - chatbot-network
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  ner:
    image: python-chat:1.0
    command: ["python3.7", "apirest.py"]
    working_dir: /ner
    healthcheck:
      test: ["CMD", "wget","-qO-", "http://ner:4999/ner?words=Quien es el alcalde de Añon.&other=True"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - chatbot-network
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  rasa:
    image: python-chat:1.0
    command: ["rasa","run","actions","--debug"] 
    working_dir: /python/administrator/ 
    volumes:
      - python:/python/
    depends_on:
      - mongodb
      - ner
    healthcheck:
      test: ["CMD", "curl", "-f", "http://rasa:5055/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    links:
      - "mongodb:mongodb"
      - "ner:ner"
    networks:
      - chatbot-network
    logging:
      options:
        max-size: "10m"
        max-file: "3"   

  api:
    image: python-chat:1.0
    command: python3.7 app.py  
    working_dir: /python/administrator
    volumes:
      - python:/python/
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api:5006/projects/5dbffabaa47f199730cc722c/models/5dbffabaa47f199730cc7584/intents/5e33fac0b88cc961afe5f69f/templates"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    links:
      - "mongodb:mongodb"
    networks:
      - chatbot-network
    logging:
      options:
        max-size: "10m"
        max-file: "3"  

  chat:
    image: python-chat:1.0    
    command: python3.7 app_chat.py 5000 /servicios/chatbot/ 
    working_dir: /python/administrator/
    environment:
      - CUDA_VISIBLE_DEVICES="-1"
    volumes:
      - python:/python/
    depends_on:
      - mongodb
      - rasa
      - ner 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://chat:5000/servicios/chatbot/status"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    links:
      - "mongodb:mongodb"
      - "rasa:rasa"
    networks:
      - chatbot-network
    logging:
      options:
        max-size: "10m"
        max-file: "3"
        

  mongodb:
    image: mongo:3.6
    volumes:
      - data:/data/db/
    ports:
      - "127.0.0.1:27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "rasa", "--eval","db.sessions.findOne({})", "--quiet"] 
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - chatbot-network
    logging:
      options:
        max-size: "10m"
        max-file: "3"
        
networks:
  chatbot-network:
    ipam:
      driver: default
      config:
        - subnet: "10.6.0.0/16"

volumes:
  data: 
    external:
      name: volume-mongodbchatbot
  python:
    external:
      name: volume-pythonchatbot
  nodejs:
    external:
      name: volume-nodejschatbot   
  nginx:
    external:
      name: volume-nginxchatbot
